// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrVP2bFzcuK4S3ma6a4BLBIEb0me2DhOA',
    appId: '1:384037448358:web:72eb9dd8a6697e1b16e267',
    messagingSenderId: '384037448358',
    projectId: 'assignment-apk',
    authDomain: 'assignment-apk.firebaseapp.com',
    storageBucket: 'assignment-apk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfogRbxf1LFEXQ2_iWDPF1lfuXaQK3zgc',
    appId: '1:384037448358:android:df21550739d57abf16e267',
    messagingSenderId: '384037448358',
    projectId: 'assignment-apk',
    storageBucket: 'assignment-apk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAHZDo7UG2FYBBdPYiCmEZCPGDIIcSNp4',
    appId: '1:384037448358:ios:757613adc83aed1216e267',
    messagingSenderId: '384037448358',
    projectId: 'assignment-apk',
    storageBucket: 'assignment-apk.appspot.com',
    iosClientId: '384037448358-6egaach2bo59o5skhsc4n1c6nuqv9og9.apps.googleusercontent.com',
    iosBundleId: 'com.example.userinfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAHZDo7UG2FYBBdPYiCmEZCPGDIIcSNp4',
    appId: '1:384037448358:ios:757613adc83aed1216e267',
    messagingSenderId: '384037448358',
    projectId: 'assignment-apk',
    storageBucket: 'assignment-apk.appspot.com',
    iosClientId: '384037448358-6egaach2bo59o5skhsc4n1c6nuqv9og9.apps.googleusercontent.com',
    iosBundleId: 'com.example.userinfo',
  );
}
